services:
  lighttracker:
    build: .
    container_name: lighttracker
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - FETCH_INTERVAL_MS=300000
      - SOURCE_URL=https://poweron.loe.lviv.ua/
    restart: unless-stopped
